# cocoapods 公用仓库地址
source 'https://github.com/CocoaPods/Specs.git'
# 私有仓库（存放podsepc文件的仓库）git地址
source 'https://github.com/situyan/MyRepo.git'

use_frameworks!
platform :ios, '10.0'
target ‘FlowerField’ do 

pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'Masonry'
pod 'YYWebImage'
pod 'FMDB'
pod 'ReactiveCocoa', '~> 2.5'
pod 'FFMDTTAPIsKit'

end

